server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_prj
    username: postgres
    password: dung28011951
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        show_sql: true
